name: test-sign

on:
  push:
    tags:
      - v*

env:
  ACR_TO_RELEASE: testnotation.azurecr.io
  ACR_REPO_TO_RELEASE: integration
  ACR_USERNAME: testnotation
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  NOTATION_EXPERIMENTAL: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare
        id: prepare
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "${VERSION}" == "${BRANCH_NAME}" ]]; then
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ref::${{ env.ACR_TO_RELEASE }}/${{ env.ACR_REPO_TO_RELEASE }}:${VERSION}
      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_TO_RELEASE }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      - name: docker build release
        run: |          
          docker build -t ${{ steps.prepare.outputs.ref }} .
          docker push ${{ steps.prepare.outputs.ref }}
      - name: AKV login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: setup AKV permissions
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AKV_NAME: testnotationAKV
        run: |
          AZURE_SERVICE_PRINCIPLE_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.["clientId"]')
          AKV_SUBSCRIPTION_ID=$(echo $AZURE_CREDENTIALS | jq -r '.["subscriptionId"]')
          echo "::add-mask::$AZURE_SERVICE_PRINCIPLE_CLIENT_ID"
          echo "::add-mask::$AKV_SUBSCRIPTION_ID"
          echo AZURE_SERVICE_PRINCIPLE_CLIENT_ID=$AZURE_SERVICE_PRINCIPLE_CLIENT_ID >> $GITHUB_ENV
          echo AKV_SUBSCRIPTION_ID=$AKV_SUBSCRIPTION_ID >> $GITHUB_ENV
          az account set -s ${{env.AKV_SUBSCRIPTION_ID}}
          az keyvault set-policy -n ${{env.AKV_NAME}} --secret-permissions get list --key-permissions sign --certificate-permissions get --spn ${{env.AZURE_SERVICE_PRINCIPLE_CLIENT_ID}}
      - name: setup notation
        uses: notation-playground/notation-actions/setup@main
        with:
          version: 1.0.0-rc.7
      - name: sign releasd image using key pair from AKV
        uses: Two-Hearts/notation-action/sign@sign
        with:
          plugin_name: azure-kv
          plugin_url: https://github.com/Azure/notation-azure-kv/releases/download/v1.0.0-rc.2/notation-azure-kv_1.0.0-rc.2_linux_amd64.tar.gz
          key_id: https://testnotationakv.vault.azure.net/keys/notationLeafCert/c585b8ad8fc542b28e41e555d9b3a1fd
          target_artifact_reference: ${{ steps.prepare.outputs.ref }}
          plugin_config: ca_certs=.github/cert-bundle/cert-bundle.crt
      - name: inspect signatures
        run: |
          notation inspect --allow-referrers-api ${{ steps.prepare.outputs.ref }}
      - name: verify released image
        uses: Two-Hearts/notation-action/verify@verify
        with:
          target_artifact_reference: ${{ steps.prepare.outputs.ref }}
          trust_policy_filepath: .github/trustpolicy/trustpolicy.json
          trust_store_name: integration
          trust_certificate_path: .github/truststore/root.crt